"""Load the editable ``rules.toml`` and build the checker chain from it.

Resolution order (first that exists wins):
  1. an explicit path argument / ``STASHER_RULES`` env / config ``rules_path``
  2. ``./rules.local.toml``        (gitignored personal overrides)
  3. ``./rules.toml``              (project starter, user-editable)
  4. the packaged ``default_rules.toml`` (always present, so loading never fails)

``rules_hash`` is a digest of the rules file *and* every referenced item-filter file,
so editing either invalidates stored evaluations and triggers a re-check.
"""

from __future__ import annotations

import hashlib
import os
import shutil
import tomllib
from pathlib import Path

from .checks import archetype_set as _archetype_set
from .checks import item_filter as _item_filter
from .checks import regex_check as _regex
from .checks import unique_roll as _unique
from .checks.base import Checker

_PACKAGE_DIR = Path(__file__).resolve().parent
_DEFAULT_RULES = _PACKAGE_DIR / "default_rules.toml"
_DEFAULT_FILTER = _PACKAGE_DIR / "default.filter"
# The packaged graded archetype set shipped with the app (regenerated by archetype_miner each
# release). Installed into the writable data dir on first run and refreshed on version upgrade.
_DEFAULT_ARCHETYPE_SET = _PACKAGE_DIR / "default_archetype_set.yaml"
# Bump when the shipped set format/content changes so existing installs pick it up (see
# ``install_archetype_set``). A 0.1.x install has no marker → treated as outdated.
ARCHETYPE_SET_VERSION = "0.2.0b9-craftability"
ARCHETYPE_SET_BAK_FILENAME = "archetype_set.bak.yaml"

# A single app-managed loot-filter file lives next to the rules file. rules.toml only
# carries `[item_filter] enabled = true/false`; the file's contents are edited/uploaded
# from the UI, so no path is exposed to the user.
FILTER_FILENAME = "stasher.filter"

# The data-driven graded archetype set (from archetype_miner). rules.toml carries
# `[archetype_set] enabled`; the user uploads + edits it on the Rules page. A pristine copy
# (.default) is kept beside it so the Rules page can "Restore defaults".
ARCHETYPE_SET_FILENAME = "archetype_set.yaml"
ARCHETYPE_SET_DEFAULT_FILENAME = "archetype_set.default.yaml"


def resolve_rules_path(
    path: str | os.PathLike[str] | None = None,
    data_dir: str | os.PathLike[str] | None = None,
) -> Path:
    """The rules file to load *and edit* (the writable target). May not exist yet:
    on a fresh install we point at ``<data_dir>/rules.toml`` and loading falls back to
    the packaged default. An existing rules file in the cwd (dev) or data dir wins."""
    if path:
        return Path(path)
    if os.environ.get("STASHER_RULES"):
        return Path(os.environ["STASHER_RULES"])
    search_dirs = [Path.cwd()]
    if data_dir:
        search_dirs.append(Path(data_dir))
    for d in search_dirs:
        for name in ("rules.local.toml", "rules.toml"):
            if (d / name).exists():
                return d / name
    return (Path(data_dir) / "rules.toml") if data_dir else Path("rules.toml")


def seed_user_rules(
    path: str | os.PathLike[str] | None = None,
    data_dir: str | os.PathLike[str] | None = None,
) -> None:
    """On first run, copy the packaged starter rules + example filter to the writable
    location so a fresh install (especially the packaged exe, whose data dir starts
    empty) ships with working example rules and an item filter. No-op if a rules file
    already exists there (e.g. the dev cwd, or a prior run)."""
    target = resolve_rules_path(path, data_dir)
    if target.exists():
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    # newline="" so Windows text mode doesn't rewrite LF as CRLF on disk.
    target.write_text(
        normalize_newlines(_DEFAULT_RULES.read_text(encoding="utf-8")),
        encoding="utf-8", newline="",
    )
    dest_filter = filter_path(target.parent)
    if not dest_filter.exists() and _DEFAULT_FILTER.exists():
        dest_filter.write_text(
            normalize_newlines(_DEFAULT_FILTER.read_text(encoding="utf-8")),
            encoding="utf-8", newline="",
        )


def install_archetype_set(
    path: str | os.PathLike[str] | None = None,
    data_dir: str | os.PathLike[str] | None = None,
    store=None,
) -> str | None:
    """Install/upgrade the **packaged** archetype set into the writable data dir.

    * fresh install (no working set) → write the working + ``.default`` copies from the package
      and stamp ``meta.archetype_set_version``;
    * outdated (stored marker missing or != ``ARCHETYPE_SET_VERSION`` — a 0.1.x set has no
      marker, and its old format lacks the rarity-floor ``mods`` catalog) → back the working copy
      up to ``archetype_set.bak.yaml``, overwrite working + ``.default`` from the package, restamp;
    * current → no-op (a user's own 0.2 customizations are preserved).

    Copies bytes verbatim (the packaged YAML is LF). Returns ``"installed"``/``"upgraded"``/None.
    No-op when the package file is absent or no ``store`` is given (can't read/write the marker)."""
    if store is None or not _DEFAULT_ARCHETYPE_SET.exists():
        return None
    base = resolve_rules_path(path, data_dir).parent
    base.mkdir(parents=True, exist_ok=True)
    working = archetype_set_path(base)
    default = archetype_set_default_path(base)
    marker = store.get_meta("archetype_set_version")
    if not (working.exists() and working.read_text(encoding="utf-8").strip()):
        shutil.copyfile(_DEFAULT_ARCHETYPE_SET, working)
        shutil.copyfile(_DEFAULT_ARCHETYPE_SET, default)
        store.set_meta("archetype_set_version", ARCHETYPE_SET_VERSION)
        return "installed"
    if marker != ARCHETYPE_SET_VERSION:
        shutil.copyfile(working, base / ARCHETYPE_SET_BAK_FILENAME)
        shutil.copyfile(_DEFAULT_ARCHETYPE_SET, working)
        shutil.copyfile(_DEFAULT_ARCHETYPE_SET, default)
        store.set_meta("archetype_set_version", ARCHETYPE_SET_VERSION)
        return "upgraded"
    return None


def normalize_newlines(text: str) -> str:
    """Collapse CRLF/CR to LF. Browsers submit textareas as CRLF and Windows text-mode
    writes can double a CR to ``\\r\\r\\n``; tomllib rejects any bare ``\\r``, so we
    normalize before parsing (and before writing) to keep files cross-platform clean."""
    return text.replace("\r\n", "\n").replace("\r", "\n")


def parse_rules_text(text: str) -> dict:
    """Parse rules TOML, raising ValueError with a friendly message on syntax errors."""
    try:
        return tomllib.loads(normalize_newlines(text))
    except tomllib.TOMLDecodeError as exc:
        raise ValueError(f"TOML syntax error: {exc}") from exc


def set_section_flag(text: str, section: str, key: str, value: bool) -> str:
    """Set ``[section] key = true/false`` in a rules TOML string (line-based, no TOML writer).

    Replaces the key if present in the section, inserts it if the section exists without it,
    or appends a new section. Used by the Settings enable/disable toggle."""
    import re

    val = "true" if value else "false"
    out: list[str] = []
    in_sec = done = False
    for line in normalize_newlines(text).splitlines():
        s = line.strip()
        if s.startswith("[") and s.endswith("]"):
            if in_sec and not done:           # leaving target section without the key
                out.append(f"{key} = {val}"); done = True
            in_sec = s == f"[{section}]"
            out.append(line); continue
        if in_sec and not done and re.match(rf"\s*{re.escape(key)}\s*=", line):
            out.append(f"{key} = {val}"); done = True; continue
        out.append(line)
    if in_sec and not done:
        out.append(f"{key} = {val}"); done = True
    if not done:
        out.append(f"[{section}]"); out.append(f"{key} = {val}")
    return "\n".join(out).rstrip("\n") + "\n"


def filter_path(base_dir: Path) -> Path:
    """The single app-managed filter file, beside the rules file."""
    return base_dir / FILTER_FILENAME


def archetype_set_path(base_dir: Path) -> Path:
    """The editable mined ArchetypeSet YAML (the working copy), beside the rules file."""
    return base_dir / ARCHETYPE_SET_FILENAME


def archetype_set_default_path(base_dir: Path) -> Path:
    """The pristine ArchetypeSet copy captured on upload, for Restore defaults."""
    return base_dir / ARCHETYPE_SET_DEFAULT_FILENAME


def item_filter_enabled(data: dict) -> bool:
    """Whether the item-filter checker is on. New form: ``[item_filter] enabled = true``;
    a legacy ``[[item_filter]]`` array counts as enabled if non-empty."""
    itf = data.get("item_filter")
    if isinstance(itf, dict):
        return bool(itf.get("enabled"))
    if isinstance(itf, list):
        return bool(itf)
    return False


def archetype_set_enabled(data: dict) -> bool:
    """Whether the mined-ArchetypeSet checker is on (``[archetype_set] enabled = true``).
    Defaults on when absent; it's a no-op until an ArchetypeSet YAML is uploaded."""
    aset = data.get("archetype_set")
    if isinstance(aset, dict):
        return bool(aset.get("enabled", True))
    return True


def build_checkers(data: dict, base_dir: Path) -> list[Checker]:
    """Build the checker chain from parsed rules. Raises ValueError on a bad rule."""
    checkers: list[Checker] = []
    if data.get("regex"):
        checkers.append(_regex.build(data["regex"]))
    if data.get("unique_roll"):
        checkers.append(_unique.build(data["unique_roll"]))
    if item_filter_enabled(data):
        fp = filter_path(base_dir)
        if fp.exists() and fp.read_text(encoding="utf-8").strip():
            checkers.append(_item_filter.build_from_file(fp))
    if archetype_set_enabled(data):
        ap = archetype_set_path(base_dir)
        if ap.exists() and ap.read_text(encoding="utf-8").strip():
            checkers.append(_archetype_set.build_from_file(ap))
    return checkers


def hash_rules(rules_bytes: bytes, data: dict, base_dir: Path) -> str:
    hasher = hashlib.sha256()
    hasher.update(rules_bytes)
    for path in (filter_path(base_dir), archetype_set_path(base_dir)):
        if path.exists():
            hasher.update(path.read_bytes())
    return hasher.hexdigest()[:16]


def load_checkers(
    path: str | os.PathLike[str] | None = None,
    data_dir: str | os.PathLike[str] | None = None,
) -> tuple[list[Checker], str]:
    """Return ``(checkers, rules_hash)`` for the resolved rules file. If the writable
    target doesn't exist yet (fresh install), load the packaged default instead while
    still resolving the filter relative to the writable dir."""
    rules_path = resolve_rules_path(path, data_dir)
    src = rules_path if rules_path.exists() else _DEFAULT_RULES
    raw_bytes = src.read_bytes()
    data = parse_rules_text(raw_bytes.decode("utf-8"))
    base_dir = rules_path.parent  # the writable dir, where the filter file lives
    checkers = build_checkers(data, base_dir)
    return checkers, hash_rules(raw_bytes, data, base_dir)
