"""Harvest real trade2 stat/pseudo ids for the pricing module from Exiled-Exchange-2's
bundled data (GitHub — NOT the PoE trade API, so no GGG rate-limit concern).

Regenerates ``stasher/pricing/data/pseudo_rules.json`` (the Phase-0 artifact). The pseudo
*ids* and per-stat explicit ids come from EE2's ``renderer/public/data/en/stats.ndjson``; the
*composition* (which stats feed each pseudo, with value multipliers) is transcribed faithfully
from EE2's ``renderer/src/web/price-check/filters/pseudo/index.ts`` (PSEUDO_RULES /
RESISTANCES_INFO / ATTRIBUTES_INFO). The ``equipment_filters`` field names (ar/es/ev/dps/
pdps/edps) were confirmed from EE2's ``trade/pathofexile-trade.ts``.

Run: ``python tools/harvest_ee2_pricing.py`` (needs network to raw.githubusercontent.com).
"""

from __future__ import annotations

import json
import urllib.request
from pathlib import Path

RAW = "https://raw.githubusercontent.com/Kvan7/Exiled-Exchange-2/master/"
STATS = "renderer/public/data/en/stats.ndjson"
OUT = Path(__file__).resolve().parent.parent / "stasher" / "pricing" / "data" / "pseudo_rules.json"

# Transcribed from EE2 pseudo/index.ts (RESISTANCES_INFO / ATTRIBUTES_INFO).
RESISTANCES_INFO = [
    ("#% to All Resistances", ["fire", "cold", "lightning"], True),
    ("#% to all Elemental Resistances", ["fire", "cold", "lightning"], False),
    ("#% to Fire Resistance", ["fire"], False),
    ("#% to Cold Resistance", ["cold"], False),
    ("#% to Lightning Resistance", ["lightning"], False),
    ("#% to Fire and Lightning Resistances", ["fire", "lightning"], False),
    ("#% to Fire and Cold Resistances", ["fire", "cold"], False),
    ("#% to Cold and Lightning Resistances", ["cold", "lightning"], False),
    ("#% to Chaos Resistance", [], True),
    ("#% to Fire and Chaos Resistances", ["fire"], True),
    ("#% to Cold and Chaos Resistances", ["cold"], True),
    ("#% to Lightning and Chaos Resistances", ["lightning"], True),
]
ATTRIBUTES_INFO = [
    ("# to all Attributes", ["str", "dex", "int"]),
    ("# to Strength", ["str"]),
    ("# to Dexterity", ["dex"]),
    ("# to Intelligence", ["int"]),
    ("# to Strength and Intelligence", ["str", "int"]),
    ("# to Strength and Dexterity", ["str", "dex"]),
    ("# to Dexterity and Intelligence", ["dex", "int"]),
]


def _fetch(path: str) -> str:
    req = urllib.request.Request(RAW + path, headers={"User-Agent": "stashler-harvest (+https://github.com/0xTosz/stashler; contact: stashlerdev@gmail.com)"})
    return urllib.request.urlopen(req, timeout=60).read().decode("utf-8")


def build() -> dict:
    ref_to_explicit: dict[str, list[str]] = {}
    ref_to_pseudo: dict[str, str] = {}
    for line in _fetch(STATS).splitlines():
        if not line.strip():
            continue
        o = json.loads(line)
        ref = o.get("ref", "")
        ids = (o.get("trade") or {}).get("ids") or {}
        if ids.get("explicit"):
            ref_to_explicit.setdefault(ref, list(ids["explicit"]))
        if ids.get("pseudo"):
            ref_to_pseudo.setdefault(ref, ids["pseudo"][0])

    def components(members: list[tuple[str, int]]) -> list[dict]:
        out: list[dict] = []
        seen: set[str] = set()
        for ref, mult in members:
            for sid in ref_to_explicit.get(ref, []):
                if sid not in seen:
                    seen.add(sid)
                    out.append({"id": sid, "mult": mult})
        return out

    aggregates = []

    # total Elemental Resistance: multiplier = number of elements the mod grants.
    ele_members = [(ref, len(els)) for ref, els, _chaos in RESISTANCES_INFO if els]
    aggregates.append({
        "pseudo_id": ref_to_pseudo["#% total Elemental Resistance"],
        "name": "total elemental resistance",
        "components": components(ele_members),
        "min_components": 1,
        "note": "fire/cold/lightning fungible; chaos separate",
    })
    # total to Chaos Resistance.
    chaos_members = [(ref, 1) for ref, _els, chaos in RESISTANCES_INFO if chaos]
    aggregates.append({
        "pseudo_id": ref_to_pseudo["#% total to Chaos Resistance"],
        "name": "total chaos resistance",
        "components": components(chaos_members),
        "min_components": 1,
    })
    # total to all Attributes: multiplier = number of attributes the mod grants.
    attr_members = [(ref, len(at)) for ref, at in ATTRIBUTES_INFO]
    aggregates.append({
        "pseudo_id": ref_to_pseudo["+# total to all Attributes"],
        "name": "total to all attributes",
        "components": components(attr_members),
        "min_components": 1,
    })

    empty = {
        "prefix": ref_to_pseudo["# Empty Prefix Modifiers"],
        "suffix": ref_to_pseudo["# Empty Suffix Modifiers"],
        "affix": ref_to_pseudo["# Empty Modifiers"],   # total open affix slots
    }
    return {
        "_comment": ("Generated by tools/harvest_ee2_pricing.py from Exiled-Exchange-2 data. "
                     "pseudo_id + component explicit ids are real trade2 ids; composition + "
                     "value multipliers transcribed from EE2 PSEUDO_RULES. Re-run to refresh."),
        "_source": "Kvan7/Exiled-Exchange-2 @ master",
        "aggregates": aggregates,
        "empty_slots": empty,
    }


def main() -> None:
    data = build()
    OUT.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8", newline="\n")
    for a in data["aggregates"]:
        print(f"{a['pseudo_id']:50s} {len(a['components'])} components")
    print("empty_slots:", data["empty_slots"])
    print("wrote", OUT)


if __name__ == "__main__":
    main()
